name: Backend + Frontend CI

on: [push, pull_request]

jobs:
  backend-unit:
    runs-on: ubuntu-latest
    env: # Add env block for Codecov token
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ci
          POSTGRES_PASSWORD: ci
          POSTGRES_DB: ci_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci

      - run: npm test -- --coverage

      - name: Upload coverage to Codecov # Added name for clarity
        if: ${{ env.CODECOV_TOKEN != '' }} # Use env var in condition
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false # Allow this step to fail without breaking the build
          token: ${{ env.CODECOV_TOKEN }} # Use env var for token

  e2e:
    needs: backend-unit
    runs-on: ubuntu-latest
    env: # Add env block for Codecov token
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install root deps
        run: npm ci

      - name: Start backend
        run: |
          npm run dev &
          echo $! > backend.pid

      - name: Run Cypress e2e
        working-directory: frontend
        run: |
          npm ci
          npm run test:e2e

      - name: Stop backend
        if: always()
        run: kill $(cat backend.pid)
